// Fragment masking utilities for GraphQL codegen
export * from "./fragment-masking";

// GraphQL codegen utilities
export * from "./gql";

// GraphQL types (generated by graphql-codegen)
// Note: Some types are re-exported from models.ts to avoid conflicts
export * from "./graphql";

// Custom model types (these override conflicting graphql.ts types)
// Export explicitly to control what takes precedence
// NOTE: RoleCode is NOT exported here to avoid conflict with graphql.ts enum
export type {
    User,
    UserProfile,
    UserPreferences,
    UserStatus,
    RoleContext,
    AuthProvider,
    Company,
    CompanyBasicInfo,
    CompanyStatus,
    CompanyRequest,
    CompanyRequestStatus,
    SessionInfo,
} from "./models";